name: ticketingapp
description: A new Flutter application.

publish_to: "none"

version: 10.0.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  camera: ^0.9.4+3
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  image_picker: ^0.8.9
  intl: ^0.18.1
  learning_text_recognition: ^0.0.3
  provider: ^6.0.5
  logging: ^1.2.0
  http: ^1.0.0
  internet_connection_checker: ^1.0.0+1
  data_table_2: ^2.5.3
  url_launcher: ^6.1.10
  device_info_plus: ^9.0.2
  # qr_code_scanner: ^1.0.1∂
  encrypt: ^5.0.1
  # platform_device_id: ^1.0.1
  unique_identifier: ^0.3.0
  shared_preferences: ^2.2.2
  another_flushbar: ^1.12.30
  geolocator: ^10.1.0
  location: ^5.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lottie: ^2.3.2
  shimmer: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
